# Generated by Django 4.2.30 on 2026-08-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['-points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_mavelikoppam', models.BooleanField(default=False, help_text='Uses special Mavelikoppam point scale: 1st=10, 2nd=7, 3rd=5. Normal games: 1st=5, 2nd=3, 3rd=2.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on events page')),
            ],
            options={
                'verbose_name': 'Onam Game',
                'verbose_name_plural': 'Onam Games',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')])),
                ('participant_name', models.CharField(blank=True, help_text='Optional — student name (can be left blank)', max_length=200)),
                ('department', models.ForeignKey(blank=True, help_text='Department the winner represents (determines points awarded)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results', to='onam.department')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='onam.onamgame')),
            ],
            options={
                'verbose_name': 'Game Result',
                'verbose_name_plural': 'Game Results',
                'ordering': ['game', 'position'],
                'unique_together': {('game', 'position')},
            },
        ),
    ]
