# Generated by Django 4.2.30 on 2026-08-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='onamgame',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date on which this game is scheduled (shown on the event card)', null=True),
        ),
    ]
