# Generated by Django 4.2.30 on 2026-08-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam', '0003_onamgame_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='onamgame',
            name='image',
            field=models.ImageField(blank=True, help_text='Background image shown on the game card (optional)', null=True, upload_to='onam_games/'),
        ),
    ]
