# Generated by Django 4.2.30 on 2026-08-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam', '0004_onamgame_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['game', 'gender', 'position'], 'verbose_name': 'Game Result', 'verbose_name_plural': 'Game Results'},
        ),
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Open (No Gender Split)'), ('M', 'Boys'), ('F', 'Girls')], default='', help_text='Leave blank for open/non-gendered events. Set to Boys or Girls for gender-split events.', max_length=1),
        ),
        migrations.AddField(
            model_name='onamgame',
            name='has_gender_categories',
            field=models.BooleanField(default=False, help_text='Enable if this game has separate results for Boys and Girls.'),
        ),
        migrations.AlterField(
            model_name='onamgame',
            name='image',
            field=models.ImageField(blank=True, help_text='Background image shown on the game card (uploaded to Supabase).', null=True, upload_to='onam_games/'),
        ),
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together={('game', 'position', 'gender')},
        ),
    ]
