# Generated by Django 4.2.30 on 2026-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onam', '0005_alter_gameresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_overall_winner', models.BooleanField(default=False, help_text='Check this box in admin to officially reveal the Overall Winner Department on the Live Scoreboard & Home Banner!', verbose_name='Show Overall Winner')),
                ('announcement_date', models.CharField(default='August 21, 2026', help_text='Date string shown when the winner announcement is still pending (e.g. August 21, 2026).', max_length=100)),
            ],
            options={
                'verbose_name': 'Onam Championship Setting',
                'verbose_name_plural': 'Onam Championship Settings',
            },
        ),
    ]
