# Generated by Django 4.2.30 on 2026-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('venue', models.CharField(max_length=200)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('registration_link', models.URLField(blank=True, help_text='Link to external registration form if applicable', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
