# Generated by Django 4.2.30 on 2026-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True, help_text='Date and time of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'event_date'], name='events_even_is_publ_442f37_idx'),
        ),
    ]
