# Generated by Django 4.2.30 on 2026-08-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_date_alter_event_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Additional event date and time')),
                ('label', models.CharField(blank=True, help_text="Optional label e.g., 'Day 2' or 'Session 2'", max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_dates', to='events.event')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
