# Generated by Django 4.2.30 on 2026-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_slug_eventdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdate',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='eventdate',
            name='time',
            field=models.TimeField(blank=True, help_text='Optional event time (12-hour format e.g. 02:20 PM)', null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='date',
            field=models.DateField(help_text='Additional event date'),
        ),
    ]
