# Generated by Django 4.2.30 on 2026-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdate_options_eventdate_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_default_poster',
            field=models.BooleanField(default=False, help_text='Use general MCSC Logo as poster (instead of custom poster image)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Upload custom poster image', null=True, upload_to='event_posters/'),
        ),
    ]
