# Generated by Django 4.2.30 on 2026-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdate_options_eventdate_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_default_poster',
            field=models.BooleanField(default=False, help_text='Check to use the official MCSC Logo as the event poster instead of a custom upload.', verbose_name='Use general MCSC Logo as poster'),
        ),
    ]
