# Generated by Django 4.2.30 on 2026-08-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_use_default_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin a ⭐ Featured badge on this event card.', verbose_name='Featured'),
        ),
    ]
