# Generated by Django 4.2.30 on 2026-08-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_use_default_poster_alter_event_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text="Mark as featured — shows a 'Featured' badge on the event card"),
        ),
    ]
