# Generated by Django 4.2.30 on 2026-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026-27', max_length=20, unique=True)),
                ('overview_text', models.TextField(help_text='Overview paragraph introducing MCSC')),
                ('membership_supervisor_names', models.CharField(help_text='Supervising faculty names', max_length=255)),
                ('election_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Council Info',
                'verbose_name_plural': 'Council Info',
            },
        ),
    ]
