# Generated by Django 4.2.30 on 2026-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.CharField(choices=[('academics', 'Academic & Curriculum'), ('facilities', 'Campus Facilities'), ('hostel', 'Hostel & Mess'), ('programs', 'Programs & Events'), ('general', 'General Concerns')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in-review', 'In Review'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['student', '-created_at'], name='grievances__student_d181a5_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status', '-created_at'], name='grievances__status_fa319e_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['category', '-created_at'], name='grievances__categor_611065_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='grievances__user_id_fb0746_idx'),
        ),
    ]
