# Generated by Django 4.2.30 on 2026-08-07 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_alter_grievance_category_alter_grievance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='grievance_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp', 'txt', 'zip', 'rar'])]),
        ),
    ]
