# Generated by Django 4.2.30 on 2026-08-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='slug',
        ),
    ]
