# Generated by Django 4.2.30 on 2026-08-07 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_eventdate_options_eventdate_time_and_more'),
        ('news', '0003_remove_newspost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional linked event to share its poster image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='events.event'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
