# Generated by Django 4.2.30 on 2026-08-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdate_options_eventdate_time_and_more'),
        ('news', '0004_alter_newspost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optionally link an event to share its poster image with this news post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='events.event'),
        ),
    ]
