# Generated by Django 4.2.30 on 2026-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspost_use_default_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Optional dedicated cover poster image for this news post', null=True, upload_to='news_posters/'),
        ),
    ]
