# Generated by Django 4.2.30 on 2026-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspost_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='use_default_poster',
            field=models.BooleanField(default=False, help_text='Use general MCSC Logo as news poster/cover if no attachment/event poster is linked'),
        ),
    ]
