# Generated by Django 4.2.30 on 2026-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspost_use_default_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Upload custom poster image for this news article', null=True, upload_to='news_posters/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='use_default_poster',
            field=models.BooleanField(default=False, help_text='Use general MCSC Logo as news poster (instead of custom poster image)'),
        ),
    ]
