# Generated by Django 4.2.30 on 2026-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026-27', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='e.g. Chairperson, Arts Secretary, Lady Rep', max_length=100)),
                ('category', models.CharField(choices=[('office_bearer', 'Office Bearer'), ('councilor_secretary', 'Councilor & Secretary'), ('year_representative', 'Year & Category Representative')], max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Upload photo or leave empty for gradient fallback', null=True, upload_to='representatives/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Used to sort within categories')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
