# Generated by Django 4.2.30 on 2026-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='position',
            field=models.CharField(help_text='e.g. Chairman, Vice Chairperson, Arts Secretary, Lady Rep', max_length=100),
        ),
    ]
