# Generated by Django 4.2.30 on 2026-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0002_alter_representative_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='academic_year',
            field=models.CharField(db_index=True, help_text='e.g. 2026-27', max_length=20),
        ),
        migrations.AlterField(
            model_name='representative',
            name='category',
            field=models.CharField(choices=[('office_bearer', 'Office Bearer'), ('councilor_secretary', 'Councilor & Secretary'), ('year_representative', 'Year & Category Representative')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='representative',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Used to sort within categories'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['academic_year', 'display_order'], name='representat_academi_745b17_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['category', 'display_order'], name='representat_categor_c69ecc_idx'),
        ),
    ]
