# Generated by Django 4.2.30 on 2026-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], db_index=True, default='student', max_length=20),
        ),
    ]
