# Generated by Django 4.2.30 on 2026-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_grievance',
            field=models.BooleanField(default=False, help_text='Grants access ONLY to the Suggestions/Grievance admin dashboard. Hides all other apps in Django Admin.', verbose_name='Can Manage Suggestions / Grievances'),
        ),
    ]
